MIN_HERO_NO = 1001        --英灵
MAX_HERO_NO = 1999
MIN_EQUIPMENT_NO = 10001  --装备
MAX_EQUIPMENT_NO = 19999
MIN_FRAGMENT_NO = 20001   --碎片
MAX_FRAGMENT_NO = 29999
MIN_SPELL_NO = 30001      --令咒
MAX_SPELL_NO = 39999
MIN_COMMODITY_NO = 40001  --其他道具
MAX_COMMODITY_NO = 49999

ITEM_QUALITY_WHITE = 1
ITEM_QUALITY_GREEN = 2
ITEM_QUALITY_BLUE = 3
ITEM_QUALITY_PURPLE = 4
ITEM_QUALITY_ORANGE = 5

ITEM_TYPE_EQUIPMENT = 1
ITEM_TYPE_FRAGMENT = 2
ITEM_TYPE_SPELL = 3
ITEM_TYPE_COMMODITY = 4

ITEM_STYPE_SPELL= 1
ITEM_STYPE_EXP= 2
ITEM_STYPE_GOLD= 3
ITEM_STYPE_OTHER= 4

EQUIPMENT_STYPE_COMMON= 1
EQUIPMENT_STYPE_FRAGMENT= 2
EQUIPMENT_STYPE_SYNTHETIC= 3
EQUIPMENT_STYPE_PRODUCT= 4


JING_FONT =  "fonts/pj.ttf"
-- 资源路径
BattleUIRes = "resource/battle/UI/"

EQUIP_ALL = 1 --全部
EQUIP_STR = 2 --筋力
EQUIP_AGI = 3 --敏捷
EQUIP_INTL = 4 --魔力
EQUIP_HP = 5 --生命
EQUIP_DC = 6 --物攻
EQUIP_MC = 7 --法强
EQUIP_DEF = 8 --护甲
EQUIP_CRIT = 9 --暴击（物理+魔法）
EQUIP_HPREC = 10 --回血
EQUIP_MPREC = 11 --回魔
EQUIP_TREAT = 12 --治疗

-- EQUIP_BOOK_TYPE = {
-- 	["str"] = EQUIP_STR,
-- 	["agi"] = EQUIP_AGI,
-- 	["intl"] = EQUIP_INTL,
-- 	["hp"] = EQUIP_HP,
-- 	["dc"] = EQUIP_DC,
-- 	["mc"] = EQUIP_MC,
-- 	["def"] = EQUIP_DEF,
-- 	["crit"] = EQUIP_CRIT,
-- 	["mcrit"] = EQUIP_CRIT,
-- 	["hprec"] = EQUIP_HPREC,
-- 	["mprec"] = EQUIP_MPREC,
-- 	["treatAddition"] = EQUIP_TREAT,

-- }

EQUIP_TYPE_NAME = {
	["str"] = "筋力",
	["agi"] = "敏捷",
    ["intl"] = "魔力",
    ["hp"] = "生命",
    ["dc"] = "物攻",
    ["mc"] = "法强",
    ["def"] = "护甲",
    ["mdef"] = "对魔力",
    ["crit"] = "物理暴击",
    ["mcrit"] = "魔法暴击",
    ["hprec"] = "回血",
    ["mprec"] = "回魔",
    ["eva"] = "闪避",
    ["hit"] = "命中",
    ["idef"] = "护甲穿透",
    ["imdef"] = "法术忽视",
    ["treatAddition"] = "治疗效果提升",
    ["manaCostReduce"] = "能量消耗降低",
    ["suck"] = "吸血",
    ["immunoSilent"]= "免疫沉默",
    ["skillLevelInc"] = "技能等级提升",
    -- ["strengthenPoint"] = "蕴含强化点数",
}

ITEM_SWEEP_ID = 40013

SCENE_TYPE_COMMON = 1
SCENE_TYPE_ELITE = 2
SCENE_TYPE_LEGEND = 3
SCENE_TYPE_ACTIVITY = 4

SCENE_TYPE_RATE = 10000
SCENE_CHAPTER_RATE = 100


HERO_SELECTED_PVP_LINE = 501
HERO_SELECTED_PVP_FIGHT = 502

PVP_MAX_COUNT = 5

NORMAL_MENU_TAG = 8888

EVENT_LISTENER_TAG_HERO_COMPOSE = 111
EVENT_LISTENER_TAG_SCENE_END = 112
EVENT_LISTENER_TAG_SCENE_FIGHT_PREPARE = 113
EVENT_LISTENER_TAG_SCENE_SWEEP = 114
EVENT_LISTENER_TAG_HERO_EQUIP = 115
EVENT_LISTENER_TAG_HERO_STAR_LEVELUP = 116
EVENT_LISTENER_TAG_HERO_FUSE = 117
EVENT_LISTENER_TAG_HERO_SKILL_LEVELUP = 118
EVENT_LISTENER_TAG_MASTER_SKILL_POINTINFO = 119
EVENT_LISTENER_TAG_PACKAGE_SELL_ITEMS = 120
EVENT_LISTENER_TAG_PACKAGE_USE_ITEMS = 121
EVENT_LISTENER_TAG_MASTER_DAILY_SIGN = 122
EVENT_LISTENER_TAG_MASTER_QUERY_LOGIN = 123
EVENT_LISTENER_TAG_MASTER_CREATE = 124
EVENT_LISTENER_TAG_MASTER_LOGIN = 125
EVENT_LISTENER_TAG_CAPSULE_FREE_DRAWINFO = 126
EVENT_LISTENER_TAG_CAPSULE_DRAW = 127
EVENT_LISTENER_TAG_HERO_COMPOSE = 128
EVENT_LISTENER_TAG_SCENE_FIGHT_END = 129
EVENT_LISTENER_TAG_SCENE_END = 130
EVENT_LISTENER_TAG_CAPSULE_DRAW_TEN = 131
EVENT_DELAIY_SIGN_TAG = 132

EVENT_LISTENER_TAG_PVP_GET_LINE = 133
EVENT_LISTENER_TAG_PVP_SET_LINE = 134
EVENT_LISTENER_TAG_PVP_GET_INFO = 135


EVENT_LISTENER_TAG_SHOP_IS_OPEN = 136
EVENT_LISTENER_TAG_SHOP_ITEM_LIST = 137
EVENT_LISTENER_TAG_SHOP_REFRESH= 138


EVENT_LISTENER_TAG_PVP_GET_ROLE = 139
EVENT_LISTENER_TAG_PVP_FIGHT = 140
EVENT_LISTENER_TAG_PVP_RESET_CD = 141
EVENT_LISTENER_TAG_PVP_RESET_COUNT = 142
EVENT_LISTENER_TAG_PVP_GET_RECORD = 143
EVENT_LISTENER_TAG_PVP_GET_RANK_LIST = 144
EVENT_LISTENER_TAG_EQUIP_ONE_BY_ONE = 145

EVENT_LISTENER_TAG_BUY_GOLD = 146
EVENT_LISTENER_TAG_BUY_HEALTH = 147


EVENT_LISTENER_TAG_DAILY_GET_LIST = 148
EVENT_LISTENER_TAG_DAILY_CLAIM = 149
EVENT_LISTENER_TAG_DAILY_AUTO_COMPLETE = 150

EVENT_LISTENER_TAG_SCENE_RESET_CD = 151

